GET http://localhost:3000/favorites
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlMGZkZmYzYi1hYzJjLTRjNDQtOWQ4MS05N2Y2ZTdlZWMxZDgiLCJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInJvbGVzIjpbIlVTRVIiLCJBRE1JTiJdLCJpYXQiOjE3NTAzNDEwNzB9.PhrAu__ObeVkS8mi7pNsCFHRlk4gQrOMa79-SSiGLaM